### PR TITLE
Fix filtering Hosts by plan_id for shortnames

### LINKED ISSUE #57: Cannot filter host by plan_id when foreman is using shortnames
[RM#29233](https://projects.theforeman.org/issues/29233)

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Fixes #57

### CODE REVIEW

File: redhat-access/app/models/redhat_access/concerns/host_managed_extensions.rb [hunk 1]
```diff
@@ -12,8 +12,10 @@ module ClassMethods
         def search_by_plan_id(key, operator, value)
           insights_plan_runner = ForemanAnsible::InsightsPlanRunner.new(Organization.current, value.to_i)
           hostname_rules_relation = insights_plan_runner.hostname_rules(insights_plan_runner.playbook)
-          host_ids = Host::Managed.where(:name => hostname_rules_relation.keys.map{|h| h.downcase}).pluck(:id)
-          { :conditions => " hosts.id IN(#{host_ids.join(',')})" }
+          hostnames = hostname_rules_relation.keys.map{|h| h.downcase}
+          hostnames.map! { |hname| hname.split('.').first } if Setting[:use_shortname_for_vms]
+          host_ids = Host::Managed.where(:name => hostnames).pluck(:id)
+          { :conditions => (host_ids.empty? ? ' 0 = 1' : " hosts.id IN(#{host_ids.join(',')})") }
```
Comment (tbrisker) [inline redhat-access/app/models/redhat_access/concerns/host_managed_extensions.rb:18]: How about passing the host names directly instead of doing an extra query to get the ids?
```suggestion
          { :conditions => (hostnames.empty? ? ' 0 = 1' : " hosts.name IN(#{hostnames.join(',')})") }
```

Comment (ezr-ondrej) [reply redhat-access/app/models/redhat_access/concerns/host_managed_extensions.rb:18]: I guess, at least we are clear about it being strictly exact match

**Review by tbrisker — APPROVED** [review]
LGTM but I don't have write access here. @rexwhite can you please take a look?

**Comment by ares** [comment]
@rexwhite any objections to merging?

**Comment by rexwhite** [comment]
The code is fine, I'm just trying to sort out another PR and I've held off merging this to avoid creating a mess.  We'd managed to collapse the branches for all releases of satellite into one but it's looking like we may have to go back to separate branches for each release.

**Comment by ezr-ondrej** [comment]
Any updates here? :)

**Comment by rexwhite** [comment]
I'm testing now.  This got a bit queued up behind the PR for moving the
branch_info endpoint into foreman.

- Rex

**Comment by ezr-ondrej** [comment]
Thanks @rexwhite ! Can you please update the BZ https://bugzilla.redhat.com/show_bug.cgi?id=1644832 once you cut a new release?

**Comment by rexwhite** [comment]
This fix is in redhat_access-2.2.19.gem, which has just been published.  This gem is valid for all releases of Satellite.
